spring.application.name=notemind-api

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notemind_ai
spring.datasource.username=postgres
spring.datasource.password=Sukhmeet@918
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# SecretKey for JWT
jwt.secretKey=${JWT_SECRET_KEY}

# AI
google.api.key=${GOOGLE_API_KEY}
openrouter.api.key=${OPENROUTER_API_KEY}

# Cloudinary
cloudinary.cloud_name=${CLOUD_NAME_CLOUDINARY}
cloudinary.api_key=${CLOUD_API_KEY_CLOUDINARY}
cloudinary.api_secret=${CLOUD_API_SECRET_CLOUDINARY}

# Redis
#spring.data.redis.host:localhost
#spring.data.redis.port:6379

